# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do


  desc "Unit & UI testin"
  lane :tests do
    scan(
      scheme: "calmo",
      workspace: "calmo.xcworkspace",
      testplan: "calmo",
      devices: ["iPhone 14"]
    )
    publish_code_covrage
  end

  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true)
  end

  # xcodebuild test -scheme calmoUITests -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -workspace calmo.xcworkspace



  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "calmo.xcodeproj")
    build_app(workspace: "calmo.xcworkspace", scheme: "calmo")
    upload_to_testflight
  end
end
