name: Run Fastlane Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      

    - name: XCODE VERSION 
      run: xcodebuild -version

    - name: List Available Simulators
      run: xcrun simctl list devices

    - name: BOOT SIM
      run:  xcrun simctl boot "iPhone 14" 

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2 # You can specify the Ruby version you need
        bundler-cache: true
        


    - name: Install Bundler and Fastlane
      run: |
        gem install bundler
        bundle install --without=documentation --path vendor/bundle

    - name: Run Fastlane Unit Tests
      run: |
        bundle exec fastlane tests # Make sure to define the "tests" lane in your Fastfile
