name: Run Fastlane Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: [self-hosted, macOS]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      

    - name: XCODE VERSION 
      run: xcodebuild -version

    - name: install pods
      run: pod install

    - name: List Available Simulators
      run: xcrun simctl list devices 
      

    - name: BOOT iphone 14
      run:  xcrun simctl boot "iPhone 14"




    - name: List Available Simulators
      run: xcrun simctl list devices 


    - name: Run Sonar Scanner
      run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=dedsecteam17 \
            -Dsonar.projectKey=DedSecTeam17_calmo-ios \
            -Dsonar.sources=. \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}    


    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.7.2 # You can specify the Ruby version you need

    # - name: Install Bundler and Fastlane
    #   run: |
    #     gem install bundler
    #     bundle install --without=documentation --path vendor/bundle

    - name: Run Fastlane Unit Tests
      run: fastlane tests
      env: 
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  
        TARGET_COVERAGE: ${{ secrets.TARGET_COVERAGE }}  


    - name: Install Sonar Scanner
      run: |
        brew install sonar-scanner        



