name: Run iOS UI Tests

on:
  pull_request:
    branches:
      - develop # Adjust this as per your branch

jobs:
  ui-tests:
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # You can specify the Ruby version you need

    - name: Install Bundler and Fastlane
      run: |
        gem install bundler
        bundle install --without=documentation --path vendor/bundle

    - name: Select Xcode Version
      run: sudo xcode-select -s '/Applications/Xcode_13.app' # Adjust the Xcode version as needed

    - name: Preboot simulator
      run: |
        xcrun simctl boot "iPhone 14" # Make sure the device matches your configuration

    - name: Run UI Tests
      run: |
        bundle exec fastlane scan --scheme "calmo" # Adjust the scheme as per your configuration
